# "prestaware/prestasdk"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: PrestaSDK Documentation
description: A simple and extendable library for developing PrestaShop modules.